// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"github.com/VarityPlatform/scraping/data/kafka"
)

// Injectors from wire.go:

func initProcessor(ctx context.Context, kafkaOpts kafka.Opts, offsetOpts kafka.OffsetManagerOpts) (*kafka.Processor, error) {
	offsetManager, err := kafka.NewOffsetManager(ctx, offsetOpts)
	if err != nil {
		return nil, err
	}
	processor, err := kafka.NewProcessor(ctx, offsetManager, kafkaOpts)
	if err != nil {
		return nil, err
	}
	return processor, nil
}

func initSink(ctx context.Context, kafkaOpts kafka.Opts, offsetOpts kafka.OffsetManagerOpts) (*kafka.BigquerySink, error) {
	offsetManager, err := kafka.NewOffsetManager(ctx, offsetOpts)
	if err != nil {
		return nil, err
	}
	bigquerySink, err := kafka.NewBigquerySink(ctx, offsetManager, kafkaOpts)
	if err != nil {
		return nil, err
	}
	return bigquerySink, nil
}
