version: "3.9"
services:
  scraper:
    build:
      context: ./src
      dockerfile: ../res/reddit-scraper/Dockerfile
    image: reddit-scraper
    environment:
      MODE: submissions
      SLEEP: 60
      SUBREDDITS: stocks
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: us-east-2
      REDDIT_USERNAME: ${REDDIT_USERNAME}
      REDDIT_PASSWORD: ${REDDIT_PASSWORD}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      REDDIT_USER_AGENT: ${REDDIT_USER_AGENT}
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      SASL_USERNAME: ${SASL_USERNAME}
      SASL_PASSWORD: ${SASL_PASSWORD}
  faust:
    build:
      context: ./src
      dockerfile: ../res/faust-processor/Dockerfile
    image: faust-processor
    environment:
      MODE: submissions
      SLEEP: 60
      SUBREDDITS: stocks
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      SASL_USERNAME: ${SASL_USERNAME}
      SASL_PASSWORD: ${SASL_PASSWORD}
