version: "3.9"
services:
  reddit-scraper:
    build:
      context: .
      dockerfile: ./res/scraping/reddit-go/Dockerfile
      target: prod
    image: reddit-scraper
    ports:
      - "8000:8000"
    environment:
      REDDIT_USERNAME: ${REDDIT_USERNAME}
      REDDIT_PASSWORD: ${REDDIT_PASSWORD}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      REDDIT_USER_AGENT: ${REDDIT_USER_AGENT}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_AUTH_KEY: ${KAFKA_AUTH_KEY}
      KAFKA_AUTH_SECRET: ${KAFKA_AUTH_SECRET}
      GOOGLE_APPLICATION_CREDENTIALS: /google/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/credentials.json:ro
  proc:
    build:
      context: .
      dockerfile: ../res/scraping/proc/Dockerfile
    image: prod
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /google/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/credentials.json:ro