version: "3.9"
services:
  scraper:
    build:
      context: ./src
      dockerfile: ../res/reddit-scraper/Dockerfile
    image: reddit-scraper
    environment:
      MODE: submissions
      SLEEP: 60
      SUBREDDITS: stocks
      REDDIT_USERNAME: ${REDDIT_USERNAME}
      REDDIT_PASSWORD: ${REDDIT_PASSWORD}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      REDDIT_USER_AGENT: ${REDDIT_USER_AGENT}
      GOOGLE_APPLICATION_CREDENTIALS: /google/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/credentials.json:ro
  beam-executor:
    build:
      context: ./src
      dockerfile: ../res/beam-executor/Dockerfile
    image: beam-executor
    environment:
      PIPELINE: submissions
      DEBUG: --debug
      GOOGLE_APPLICATION_CREDENTIALS: /google/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/credentials.json:ro