version: "3.9"
services:
  scraper:
    build:
      context: ./src
      dockerfile: ../res/reddit-scraper/Dockerfile
    image: reddit-scraper
    environment:
      MODE: submissions
      SLEEP: 60
      SUBREDDITS: stocks
      REDDIT_USERNAME: ${REDDIT_USERNAME}
      REDDIT_PASSWORD: ${REDDIT_PASSWORD}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      REDDIT_USER_AGENT: ${REDDIT_USER_AGENT}
      GOOGLE_APPLICATION_CREDENTIALS: /google/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/credentials.json:ro
  historical-scraper:
    build:
      context: ./src
      dockerfile: ../res/historical-reddit-scraper/Dockerfile
    image: historical-reddit-scraper
    environment:
      MODE: submissions
      SUBREDDIT: stocks
      YEAR: 2021
      MONTH: 1
      DAY: 1
      GOOGLE_APPLICATION_CREDENTIALS: /google/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/credentials.json:ro
  beam-executor:
    build:
      context: ./src
      dockerfile: ../res/beam-executor/Dockerfile
    image: beam-executor
    environment:
      PIPELINE: submissions
      DEBUG: --debug
      GOOGLE_APPLICATION_CREDENTIALS: /google/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/credentials.json:ro
  postgres:
    image: postgres:10
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase_usr
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ~/data/postgresql:/var/lib/postgresql
  metabase:
    depends_on:
      - postgres
    image: metabase/metabase
    ports:
      - "3000:3000"
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_usr
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    ports:
      - "3001:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@example.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}