version: "3.9"
services:
  reddit-scraper:
    build:
      context: .
      dockerfile: ./res/scraping/reddit-scraper/Dockerfile
      target: prod
    image: reddit-scraper
    network_mode: host
    environment:
      REDDIT_USERNAME: ${REDDIT_USERNAME}
      REDDIT_PASSWORD: ${REDDIT_PASSWORD}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      REDDIT_USER_AGENT: ${REDDIT_USER_AGENT}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_AUTH_KEY: ${KAFKA_AUTH_KEY}
      KAFKA_AUTH_SECRET: ${KAFKA_AUTH_SECRET}
      GOOGLE_APPLICATION_CREDENTIALS: /google/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/credentials.json:ro
  proc:
    build:
      context: .
      dockerfile: ./res/scraping/proc/Dockerfile
      target: prod
    image: proc
    network_mode: host
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_AUTH_KEY: ${KAFKA_AUTH_KEY}
      KAFKA_AUTH_SECRET: ${KAFKA_AUTH_SECRET}
      POSTGRES_ADDRESS: ${POSTGRES_ADDRESS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GOOGLE_APPLICATION_CREDENTIALS: /google/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/credentials.json:ro

  historical-reddit-scraper:
    build:
      context: .
      dockerfile: ./res/scraping/historical-reddit-scraper/Dockerfile
      target: prod
    network_mode: host
    image: historical-reddit-scraper
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_AUTH_KEY: ${KAFKA_AUTH_KEY}
      KAFKA_AUTH_SECRET: ${KAFKA_AUTH_SECRET}
      GOOGLE_APPLICATION_CREDENTIALS: /google/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/credentials.json:ro