// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"github.com/VarityPlatform/scraping/scrapers"
	"github.com/vartanbeno/go-reddit/v2/reddit"
)

// Injectors from wire.go:

func initSubmissionsScraper(ctx context.Context, redditCredentials reddit.Credentials, memoryOpts scrapers.MemoryOpts) (*scrapers.RedditSubmissionsScraper, error) {
	memory, err := scrapers.NewMemory(ctx, memoryOpts)
	if err != nil {
		return nil, err
	}
	redditSubmissionsScraper, err := scrapers.NewRedditSubmissionsScraper(redditCredentials, memory)
	if err != nil {
		return nil, err
	}
	return redditSubmissionsScraper, nil
}

func initCommentsScraper(ctx context.Context, redditCredentials reddit.Credentials, memoryOpts scrapers.MemoryOpts) (*scrapers.RedditCommentsScraper, error) {
	memory, err := scrapers.NewMemory(ctx, memoryOpts)
	if err != nil {
		return nil, err
	}
	redditCommentsScraper, err := scrapers.NewRedditCommentsScraper(redditCredentials, memory)
	if err != nil {
		return nil, err
	}
	return redditCommentsScraper, nil
}
