"""Create cohort memberships table

Revision ID: 49c8f7188ea7
Revises: bd4fedc9d0fc
Create Date: 2021-09-18 10:56:35.620177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c8f7188ea7'
down_revision = 'bd4fedc9d0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_memberships',
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('subreddit', sa.String(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('cohort', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('author_id', 'subreddit', 'month', 'cohort')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cohort_memberships')
    # ### end Alembic commands ###
