"""Add short_name column to tickers table

Revision ID: 67e3b1fe5a35
Revises: cb188d5f3a76
Create Date: 2021-05-22 11:20:21.285230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e3b1fe5a35'
down_revision = 'cb188d5f3a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('short_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickers', 'short_name')
    # ### end Alembic commands ###
