"""add tickers table

Revision ID: 7d92732a8eec
Revises: 
Create Date: 2021-05-21 16:23:34.790517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d92732a8eec"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickers",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=False),
        sa.Column("exchange_name", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("scraped_on", sa.Date(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=True),
        sa.Column("cik", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "exchange"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tickers")
    # ### end Alembic commands ###
