"""Create initial schema

Revision ID: bd4fedc9d0fc
Revises: 
Create Date: 2021-07-27 19:16:32.954528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd4fedc9d0fc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickers",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=True),
        sa.Column("exchange_name", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("scraped_on", sa.Date(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=True),
        sa.Column("cik", sa.String(), nullable=True),
        sa.Column("short_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tickers")
    # ### end Alembic commands ###
