// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"github.com/VarityPlatform/scraping/data/kafka"
	"github.com/VarityPlatform/scraping/scrapers"
	"github.com/VarityPlatform/scraping/scrapers/reddit/historical"
)

// Injectors from wire.go:

func initSubmissionsScraper(ctx context.Context, memoryOpts scrapers.MemoryOpts) (*historical.SubmissionsScraper, error) {
	memory, err := scrapers.NewMemory(ctx, memoryOpts)
	if err != nil {
		return nil, err
	}
	submissionsScraper, err := historical.NewSubmissionsScraper(memory)
	if err != nil {
		return nil, err
	}
	return submissionsScraper, nil
}

func initCommentsScraper(ctx context.Context, memoryOpts scrapers.MemoryOpts) (*historical.CommentsScraper, error) {
	memory, err := scrapers.NewMemory(ctx, memoryOpts)
	if err != nil {
		return nil, err
	}
	commentsScraper, err := historical.NewCommentsScraper(memory)
	if err != nil {
		return nil, err
	}
	return commentsScraper, nil
}

func initPublisher(ctx context.Context, opts kafka.PublisherOpts) (*kafka.Publisher, error) {
	publisher, err := kafka.NewPublisher(opts)
	if err != nil {
		return nil, err
	}
	return publisher, nil
}
