name: Test Python

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install install pylint pytest
        python -m pip install install -r requirements.txt
    - name: Test with PyTest
      run: |
        export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/src
        python -m pytest src
    - name: Analysing the code with pylint
      run: |
        cd src
        python -m pylint *
