name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install linux dependencies
      run: |
      sudo apt-get update \
      DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends \
        software-properties-common \
      sudo add-apt-repository -y ppa:deadsnakes \
      DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends \
        build-essential autoconf libtool pkg-config \
        librocksdb-dev \
        libsnappy-dev \
        zlib1g-dev \
        libbz2-dev \
        liblz4-dev \
      sudo apt-get clean \
      sudo rm -rf /var/lib/apt/lists/* \
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint src
        pytest src
