name: Validation Workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test-python:
    name: Test and Lint Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install install pylint pytest
        python -m pip install install -r requirements.txt
    - name: Test with PyTest
      env:
        REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
        REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      run: cd src && python -m pytest .
    - name: Analysing the code with pylint
      run: cd src && python -m pylint *

  test-go:
    name: Test and Lint Go modules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Test
      run: go test -v go/...
    - name: Check formatting
      run: test -n "$(gofmt -l -s go)" && echo $(gofmt -l -s go) && exit 1

  build-images:
    needs: test-python
    name: Validate Docker Images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Validate the Docker images
    - name: Build Images
      run: |
        gcloud auth configure-docker
        export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
        echo Building ${TAG}...
        ./build.sh --prod --release $TAG
