name: Test and Validate

on:
  push:
    branches:

jobs:
  test-python:
    name: Test and Lint Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install install pylint pytest pylint_pytest
    - name: Analysing the code with pylint
      run: cd src && python -m pylint *

  lint-go:
    name: Lint Go modules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Lint
      run: |
        go get -u golang.org/x/lint/golint
        LINT=`golint ./...` && echo $LINT && test `echo -n $LINT | wc -c` -eq 0

  test-go:
    name: Unit Test Go modules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Test
      run: cd scraping && go test ./...
  
  build-images:
    name: Validate Docker Images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Validate the Docker images
    - name: Build Images
      run: |
        gcloud auth configure-docker
        export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
        echo Building ${TAG}...
        ./build.sh --release $TAG
